export const PERMISSIONS = {
    DOCUMENT_UPLOAD: 'document.upload',
    DOCUMENT_VIEW: 'document.view',
    DOCUMENT_DELETE: 'document.delete',
    DOCUMENT_PREVIEW: 'document.preview',
    DOCUMENT_SHARE: 'document.share',
    CHAT_USE: 'chat.use',
    TEAM_MANAGE: 'team.manage',
    ORG_DOCUMENTS_VIEW: 'org.documents.view',
    DEPARTMENT_MANAGE: 'department.manage',
    DEPARTMENT_VIEW: 'department.view',
    PAGE_DASHBOARD: 'page.dashboard',
    PAGE_DOCUMENTS: 'page.documents',
    PAGE_CHAT: 'page.chat',
    PAGE_ACTIVITY: 'page.activity',
    PAGE_DEPARTMENTS: 'page.departments',
    PAGE_PLANS: 'page.plans',
    PAGE_EMAIL_REPORTS: 'page.email_reports',
    PAGE_INTEGRATIONS: 'page.integrations',
    PAGE_SETTINGS: 'page.settings',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PAGE_PERMISSIONS: PermissionKey[] = [
    PERMISSIONS.PAGE_DASHBOARD,
    PERMISSIONS.PAGE_DOCUMENTS,
    PERMISSIONS.PAGE_CHAT,
    PERMISSIONS.PAGE_ACTIVITY,
    PERMISSIONS.PAGE_DEPARTMENTS,
    PERMISSIONS.PAGE_PLANS,
    PERMISSIONS.PAGE_EMAIL_REPORTS,
    PERMISSIONS.PAGE_INTEGRATIONS,
    PERMISSIONS.PAGE_SETTINGS,
];

const PAGE_EMPLOYEE: Partial<Record<PermissionKey, boolean>> = {
    [PERMISSIONS.PAGE_DASHBOARD]: true,
    [PERMISSIONS.PAGE_DOCUMENTS]: true,
    [PERMISSIONS.PAGE_CHAT]: true,
    [PERMISSIONS.PAGE_ACTIVITY]: false,
    [PERMISSIONS.PAGE_DEPARTMENTS]: false,
    [PERMISSIONS.PAGE_PLANS]: false,
    [PERMISSIONS.PAGE_EMAIL_REPORTS]: false,
    [PERMISSIONS.PAGE_INTEGRATIONS]: false,
    [PERMISSIONS.PAGE_SETTINGS]: false,
};

const PAGE_LEADER: Partial<Record<PermissionKey, boolean>> = {
    [PERMISSIONS.PAGE_DASHBOARD]: true,
    [PERMISSIONS.PAGE_DOCUMENTS]: true,
    [PERMISSIONS.PAGE_CHAT]: true,
    [PERMISSIONS.PAGE_ACTIVITY]: true,
    [PERMISSIONS.PAGE_DEPARTMENTS]: true,
};

export const DEFAULT_TEAM_PERMISSIONS: Record<PermissionKey, boolean> = {
    ...PAGE_EMPLOYEE,
    [PERMISSIONS.DOCUMENT_UPLOAD]: true,
    [PERMISSIONS.DOCUMENT_VIEW]: true,
    [PERMISSIONS.DOCUMENT_DELETE]: true,
    [PERMISSIONS.DOCUMENT_PREVIEW]: true,
    [PERMISSIONS.DOCUMENT_SHARE]: false,
    [PERMISSIONS.CHAT_USE]: true,
    [PERMISSIONS.TEAM_MANAGE]: false,
    [PERMISSIONS.ORG_DOCUMENTS_VIEW]: false,
    [PERMISSIONS.DEPARTMENT_MANAGE]: false,
    [PERMISSIONS.DEPARTMENT_VIEW]: true,
    [PERMISSIONS.PAGE_PLANS]: false,
    [PERMISSIONS.PAGE_EMAIL_REPORTS]: false,
    [PERMISSIONS.PAGE_INTEGRATIONS]: false,
    [PERMISSIONS.PAGE_SETTINGS]: false,
} as Record<PermissionKey, boolean>;

export const DEFAULT_ADMIN_PERMISSIONS: Record<PermissionKey, boolean> = {
    [PERMISSIONS.DOCUMENT_UPLOAD]: true,
    [PERMISSIONS.DOCUMENT_VIEW]: true,
    [PERMISSIONS.DOCUMENT_DELETE]: true,
    [PERMISSIONS.DOCUMENT_PREVIEW]: true,
    [PERMISSIONS.DOCUMENT_SHARE]: true,
    [PERMISSIONS.CHAT_USE]: true,
    [PERMISSIONS.TEAM_MANAGE]: true,
    [PERMISSIONS.ORG_DOCUMENTS_VIEW]: true,
    [PERMISSIONS.DEPARTMENT_MANAGE]: true,
    [PERMISSIONS.DEPARTMENT_VIEW]: true,
    [PERMISSIONS.PAGE_DASHBOARD]: true,
    [PERMISSIONS.PAGE_DOCUMENTS]: true,
    [PERMISSIONS.PAGE_CHAT]: true,
    [PERMISSIONS.PAGE_ACTIVITY]: true,
    [PERMISSIONS.PAGE_DEPARTMENTS]: true,
    [PERMISSIONS.PAGE_PLANS]: true,
    [PERMISSIONS.PAGE_EMAIL_REPORTS]: true,
    [PERMISSIONS.PAGE_INTEGRATIONS]: true,
    [PERMISSIONS.PAGE_SETTINGS]: true,
};

export const DEFAULT_EMPLOYEE_PERMISSIONS: Record<PermissionKey, boolean> = {
    ...DEFAULT_TEAM_PERMISSIONS,
    ...PAGE_EMPLOYEE,
    [PERMISSIONS.DOCUMENT_SHARE]: false,
    [PERMISSIONS.DEPARTMENT_VIEW]: true,
};

export const DEFAULT_LEADER_PERMISSIONS: Record<PermissionKey, boolean> = {
    ...DEFAULT_TEAM_PERMISSIONS,
    ...PAGE_LEADER,
    [PERMISSIONS.DOCUMENT_SHARE]: true,
    [PERMISSIONS.DEPARTMENT_VIEW]: true,
    [PERMISSIONS.DEPARTMENT_MANAGE]: false,
};

export const DEFAULT_MANAGER_PERMISSIONS: Record<PermissionKey, boolean> = {
    ...DEFAULT_TEAM_PERMISSIONS,
    ...PAGE_LEADER,
    [PERMISSIONS.DOCUMENT_SHARE]: true,
    [PERMISSIONS.DEPARTMENT_VIEW]: true,
    [PERMISSIONS.DEPARTMENT_MANAGE]: false,
    [PERMISSIONS.TEAM_MANAGE]: false,
    [PERMISSIONS.ORG_DOCUMENTS_VIEW]: true,
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

/** Only these can be toggled for team members in the Team UI. */
export const TEAM_MEMBER_EDITABLE_PERMISSIONS: PermissionKey[] = [
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.CHAT_USE,
];

export const ORG_ROLE_EDITABLE_PERMISSIONS: PermissionKey[] = [
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.DOCUMENT_SHARE,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.ORG_DOCUMENTS_VIEW,
    ...PAGE_PERMISSIONS,
];

export const ORG_ROLE_PAGE_PERMISSIONS = PAGE_PERMISSIONS;

export const ORG_ROLE_FEATURE_PERMISSIONS: PermissionKey[] = [
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.DOCUMENT_SHARE,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.ORG_DOCUMENTS_VIEW,
];
